#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
#    Copyright 2011 Sasu Karttunen <sasu.karttunen@tpnet.fi>
#
#    This file is part of D-Bus Python Weather API Service (pywapi-dbus).
#
#    pywapi-dbus is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    pywapi-dbus is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with pywapi-dbus.  If not, see <http://www.gnu.org/licenses/>.

from sys import argv, exit
from os import path, makedirs, environ
from pywapidbus.daemon import Daemon

pidfile = path.join(environ['HOME'], '.pywapi-dbus', 'pywapi-dbus.pid')
directoryname = path.dirname(pidfile)
if not path.exists(directoryname):
    makedirs(directoryname)

pidfileString = str(pidfile)

 
class MyDaemon(Daemon):
        def run(self):
                import pywapidbus.main
 
if __name__ == "__main__":
        daemon = MyDaemon(pidfileString)
        if len(argv) == 2:
                if 'start' == argv[1]:
                        daemon.start()
                elif 'stop' == argv[1]:
                        daemon.stop()
                elif 'restart' == argv[1]:
                        daemon.restart()
                else:
                        print "Unknown command"
                        exit(2)
                exit(0)
        else:
                print "usage: %s start|stop|restart" % argv[0]
                exit(2)